# Brick DVC stages
# See https://dvc.org/doc/user-guide/project-structure/dvcyaml-files#pipelines-files-dvcyaml

# The complete process can be executed using:
# dvc repro
# If you want to force redoing the process use 
# dvc repro -f
# Individual stage can be executed using: 
# dvc repro <stage>

stages:
  download:
    cmd: stages/01_download.sh
    deps:
      - stages/01_download.sh
    outs:
      - download
  csv:
    cmd: stages/02_csv.sh
    deps:
      - stages/02_csv.sh
      - stages/02_flatten-openalex-jsonl.py
      - download
    outs:
      - csv
  brick:
    cmd: stages/03_brick.sh
    deps:
      - stages/03_brick.sh
      - stages/03_csv2parquet.py
      - csv
    outs:
      - brick
